/**
 * 演示了两种 pre-render: Static Generation, Server-side rendering
 */
import Head from "next/head";

interface IProps {
  info: string;
}

export default function Welcome(props: IProps) {
  const { info } = props;
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div style={{ width: "100vw", textAlign: "center", marginTop: "90px" }}>
        <h2>Hello World</h2>
        <h5>Created By {info}</h5>
      </div>
    </>
  );
}

// Static Generation
// export async function getStaticProps() {
//   /* 这里可以 await 异步请求 */
//   /* 该函数只有在 npm run build 构建时执行，上线后任何请求都不会触发该函数的执行 */
//   return {
//     props: {
//       info: "yiTuChuan",
//     },
//   };
// }

// Server-side rendering
export async function getServerSideProps() {
  /* 这里可以 await 异步请求 */
  /* 该函数在每次发送请求时都会执行 */
  return {
    props: {
      info: "Nasir",
    },
  };
}
